// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatisticalProcess.Infrastructure.EntityFramework.Context;

#nullable disable

namespace StatisticalProcess.Infrastructure.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20250412153129_ImproveValuePrecision4")]
    partial class ImproveValuePrecision4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("StatisticalProcess")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StatisticProcess.Domain.Entities.QuoteData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("measureId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("measureId");

                    b.ToTable("QuoteData", "StatisticalProcess");
                });

            modelBuilder.Entity("StatisticProcess.Domain.Entitys.MeasurementData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MeasurementDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementDateTime");

                    b.ToTable("MeasurementData", "StatisticalProcess");
                });

            modelBuilder.Entity("StatisticProcess.Domain.Entities.QuoteData", b =>
                {
                    b.HasOne("StatisticProcess.Domain.Entitys.MeasurementData", "Measure")
                        .WithMany("Quotes")
                        .HasForeignKey("measureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measure");
                });

            modelBuilder.Entity("StatisticProcess.Domain.Entitys.MeasurementData", b =>
                {
                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
